### PR TITLE
Add ✨new✨ cogs for coin management and utility features; update versi…

### PR DESCRIPTION
**Pull request by christofferbuen**
…on and config✨

### CODE REVIEW

**Review by christofferbuen — COMMENTED** [review]
LGTM!
👍
Thumbs Up
👍🏻
Thumbs Up: Light Skin Tone
👍🏼
Thumbs Up: Medium-Light Skin Tone
👍🏽
Thumbs Up: Medium Skin Tone
👍🏿
Thumbs Up: Dark Skin Tone
👍🏾
Thumbs Up: Medium-Dark Skin Tone

**Comment by christofferbuen** [comment]
Pluss litt andre greier

**Review by christofferbuen — COMMENTED** [review]
Refaktorert koden og lagt til en hel haug med drit

**Review by MartinRovang — APPROVED** [review]
LGTM

**Review by DanRJ — APPROVED** [review]

**Pull request merged**
